# Generated by Django 4.0.10 on 2023-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories', models.IntegerField()),
                ('total_fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydate', models.FloatField()),
                ('sugars', models.FloatField()),
                ('fiber', models.FloatField()),
                ('nutrition_score', models.FloatField()),
            ],
        ),
    ]
