# Generated by Django 4.0.10 on 2023-03-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='carbohydate',
            new_name='carbohydrate',
        ),
    ]
